# The URL the site will be built for
base_url = "https://ali.ghaffaari.me"
title = "cartoonist"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Theme
theme = "apollo"
taxonomies = [{ name = "tags" }] 

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
theme = "auto"
favicon = "/icon/favicon.png"
mathjax = true
mathjax_dollar_inline_enable = true
socials = [
# Configure socials here
    { name = "google-scholar", url = "https://scholar.google.de/citations?user=dvEu4aMAAAAJ", icon = "google-scholar" },
    { name = "ORCID", url = "https://orcid.org/0000-0002-0540-6515", icon = "orcid" },
    { name = "github", url = "https://github.com/cartoonist/", icon = "github" },
    { name = "linkedin", url = "https://linkedin.com/in/alighaffaari/", icon = "linkedin" },
    { name = "email", url = "mailto:ali@ghaffaari.me", icon = "email" },
]
menu = [
# Configure menu bar here
    { name = "/cv", url = "/file/AliGhaffaari_Resume.pdf", weight = 1 },
    #{ name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    #{ name = "/contact", url = "/contact", weight = 4 },
]
